openapi: 3.0.0
info:
  title: DevifyX Banking API
  version: 1.0.0
  description: API documentation for the banking system

servers:
  - url: http://localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        balance:
          type: number
    Transfer:
      type: object
      properties:
        fromAccountId:
          type: integer
        toAccountId:
          type: integer
        amount:
          type: number
        type:
          type: string
          enum: [internal, external]
        scheduledAt:
          type: string
          format: date-time
        recurring:
          type: boolean
        fee:
          type: number
    Transaction:
      type: object
      properties:
        id:
          type: integer
        fromAccountId:
          type: integer
        toAccountId:
          type: integer
        amount:
          type: number
        type:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

security:
  - bearerAuth: []

tags:
  - name: Auth
  - name: Accounts
  - name: Transfers
  - name: Transactions
  
paths:
  /api/auth/signup:
    post:
      tags:
        - Auth
      summary: Signup a new user
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: John Doe
              email: john@example.com
              password: 123456
      responses:
        '201':
          description: User created

  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login success
        '401':
          description: Invalid credentials

  /api/accounts:
   post:
    tags:
      - Accounts
    summary: Create account
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          example:
            type: "savings"
            initialBalance: 1000
            currency: "USD"
    responses:
      '201':
        description: Account created

  /api/transfers:
    post:
      tags:
        - Transfers
      summary: Initiate a transfer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            example:
              fromAccountId: 1
              toAccountId: 2
              amount: 100
              type: "internal"
              scheduledAt: "2025-06-30T12:00:00Z"
              recurring: false
      responses:
        '201':
          description: Transfer created

  /api/transactions:
    get:
      tags:
        - Transactions
      summary: Fetch transaction history
      security:
        - bearerAuth: []
      parameters:
        - name: accountId
          in: query
          required: false
          schema:
            type: integer
        - name: type
          in: query
          required: false
          schema:
            type: string
        - name: status
          in: query
          required: false
          schema:
            type: string
        - name: startDate
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: export
          in: query
          required: false
          schema:
            type: string
            enum: [csv]
      responses:
        '200':
          description: List of transactions
